import type { NextApiRequest, NextApiResponse } from 'next';

type RankingRow = Readonly<{
  player: Readonly<{
    fullName: string;
  }>;
  rank: number;
}>;

type SourcePlayer = Readonly<{
  first_name: string;
  last_name: string;
  rank: number;
}>;

const players: SourcePlayer[] = [
  { first_name: 'Scottie', last_name: 'Scheffler', rank: 1 },
  { first_name: 'Rory', last_name: 'McIlroy', rank: 2 },
  { first_name: 'Matt', last_name: 'Fitzpatrick', rank: 3 },
  { first_name: 'Cameron', last_name: 'Young', rank: 4 },
  { first_name: 'Russell', last_name: 'Henley', rank: 5 },
  { first_name: 'Chris', last_name: 'Gotterup', rank: 6 },
  { first_name: 'Collin', last_name: 'Morikawa', rank: 7 },
  { first_name: 'Wyndham', last_name: 'Clark', rank: 8 },
  { first_name: 'Tommy', last_name: 'Fleetwood', rank: 9 },
  { first_name: 'Justin', last_name: 'Rose', rank: 10 },
  { first_name: 'Jon', last_name: 'Rahm', rank: 11 },
  { first_name: 'Viktor', last_name: 'Hovland', rank: 12 },
  { first_name: 'J.J.', last_name: 'Spaun', rank: 13 },
  { first_name: 'Xander', last_name: 'Schauffele', rank: 14 },
  { first_name: 'Robert', last_name: 'MacIntyre', rank: 15 },
  { first_name: 'Ben', last_name: 'Griffin', rank: 16 },
  { first_name: 'Aaron', last_name: 'Rai', rank: 17 },
  { first_name: 'Sam', last_name: 'Burns', rank: 18 },
  { first_name: 'Justin', last_name: 'Thomas', rank: 19 },
  { first_name: 'Ludvig', last_name: 'Aberg', rank: 20 },
  { first_name: 'Si Woo', last_name: 'Kim', rank: 21 },
  { first_name: 'Tyrrell', last_name: 'Hatton', rank: 22 },
  { first_name: 'Sepp', last_name: 'Straka', rank: 23 },
  { first_name: 'Min Woo', last_name: 'Lee', rank: 24 },
  { first_name: 'Alex', last_name: 'Noren', rank: 25 },
  { first_name: 'Patrick', last_name: 'Reed', rank: 26 },
  { first_name: 'Kristoffer', last_name: 'Reitan', rank: 27 },
  { first_name: 'Ryan', last_name: 'Gerard', rank: 28 },
  { first_name: 'Akshay', last_name: 'Bhatia', rank: 29 },
  { first_name: 'Jacob', last_name: 'Bridgeman', rank: 30 },
  { first_name: 'Hideki', last_name: 'Matsuyama', rank: 31 },
  { first_name: 'Harris', last_name: 'English', rank: 32 },
  { first_name: 'Tom', last_name: 'Kim', rank: 33 },
  { first_name: 'J.T.', last_name: 'Poston', rank: 34 },
  { first_name: 'Nicolai', last_name: 'Hojgaard', rank: 35 },
  { first_name: 'Kurt', last_name: 'Kitayama', rank: 36 },
  { first_name: 'Bryson', last_name: 'DeChambeau', rank: 37 },
  { first_name: 'Patrick', last_name: 'Cantlay', rank: 38 },
  { first_name: 'Maverick', last_name: 'McNealy', rank: 39 },
  { first_name: 'Bud', last_name: 'Cauley', rank: 40 },
  { first_name: 'Keegan', last_name: 'Bradley', rank: 41 },
  { first_name: 'Rickie', last_name: 'Fowler', rank: 42 },
  { first_name: 'Gary', last_name: 'Woodland', rank: 43 },
  { first_name: 'Alex', last_name: 'Smalley', rank: 44 },
  { first_name: 'Jake', last_name: 'Knapp', rank: 45 },
  { first_name: 'Shane', last_name: 'Lowry', rank: 46 },
  { first_name: 'Sam', last_name: 'Stevens', rank: 47 },
  { first_name: 'Joaquin', last_name: 'Niemann', rank: 48 },
  { first_name: 'Daniel', last_name: 'Berger', rank: 49 },
  { first_name: 'Marco', last_name: 'Penge', rank: 50 },
  { first_name: 'Jordan', last_name: 'Spieth', rank: 51 },
  { first_name: 'Nicolas', last_name: 'Echavarria', rank: 52 },
  { first_name: 'Corey', last_name: 'Conners', rank: 53 },
  { first_name: 'Jason', last_name: 'Day', rank: 54 },
  { first_name: 'Michael', last_name: 'Kim', rank: 55 },
  { first_name: 'Ryan', last_name: 'Fox', rank: 56 },
  { first_name: 'Adam', last_name: 'Scott', rank: 57 },
  { first_name: 'John', last_name: 'Keefer', rank: 58 },
  { first_name: 'Eugenio', last_name: 'Lopez-Chacarra', rank: 59 },
  { first_name: 'Michael', last_name: 'Brennan', rank: 60 },
  { first_name: 'Pierceson', last_name: 'Coody', rank: 61 },
  { first_name: 'Ryo', last_name: 'Hisatsune', rank: 62 },
  { first_name: 'Matthew', last_name: 'McCarty', rank: 63 },
  { first_name: 'Brian', last_name: 'Harman', rank: 64 },
  { first_name: 'Alex', last_name: 'Fitzpatrick', rank: 65 },
  { first_name: 'David', last_name: 'Puig', rank: 66 },
  { first_name: 'Nick', last_name: 'Taylor', rank: 67 },
  { first_name: 'Keith', last_name: 'Mitchell', rank: 68 },
  { first_name: 'Andrew', last_name: 'Novak', rank: 69 },
  { first_name: 'Michael', last_name: 'Thorbjornsen', rank: 70 },
  { first_name: 'Eric', last_name: 'Cole', rank: 71 },
  { first_name: 'Matt', last_name: 'Wallace', rank: 72 },
  { first_name: 'Sami', last_name: 'Valimaki', rank: 73 },
  { first_name: 'Max', last_name: 'Homa', rank: 74 },
  { first_name: 'Matti', last_name: 'Schmid', rank: 75 },
  { first_name: 'Harry', last_name: 'Hall', rank: 76 },
  { first_name: 'Max', last_name: 'Greyserman', rank: 77 },
  { first_name: 'Jordan L.', last_name: 'Smith', rank: 78 },
  { first_name: 'Steven', last_name: 'Fisk', rank: 79 },
  { first_name: 'Thomas', last_name: 'Detry', rank: 80 },
  { first_name: 'Sahith', last_name: 'Theegala', rank: 81 },
  { first_name: 'Casey', last_name: 'Jarvis', rank: 82 },
  { first_name: 'Aldrich', last_name: 'Potgieter', rank: 83 },
  { first_name: 'Mac', last_name: 'Meissner', rank: 84 },
  { first_name: 'Jayden Trey', last_name: 'Schaper', rank: 85 },
  { first_name: 'Sungjae', last_name: 'Im', rank: 86 },
  { first_name: 'Taylor', last_name: 'Pendrith', rank: 87 },
  { first_name: 'Rasmus', last_name: 'Hojgaard', rank: 88 },
  { first_name: 'Lucas', last_name: 'Glover', rank: 89 },
  { first_name: 'Keita', last_name: 'Nakajima', rank: 90 },
  { first_name: 'Rasmus', last_name: 'Neergaard-Petersen', rank: 91 },
  { first_name: 'Patrick', last_name: 'Rodgers', rank: 92 },
  { first_name: 'Andrew', last_name: 'Putnam', rank: 93 },
  { first_name: 'Shaun', last_name: 'Norris', rank: 94 },
  { first_name: 'John', last_name: 'Parry', rank: 95 },
  { first_name: 'Christiaan', last_name: 'Bezuidenhout', rank: 96 },
  { first_name: 'Lucas', last_name: 'Herbert', rank: 97 },
  { first_name: 'Stephan', last_name: 'Jaeger', rank: 98 },
  { first_name: 'Ricky', last_name: 'Castillo', rank: 99 },
  { first_name: 'Blades', last_name: 'Brown', rank: 100 },
  { first_name: 'Rico', last_name: 'Hoey', rank: 101 },
  { first_name: 'Max', last_name: 'McGreevy', rank: 102 },
  { first_name: 'Sudarshan', last_name: 'Yellamaraju', rank: 103 },
  { first_name: 'Austin', last_name: 'Smotherman', rank: 104 },
  { first_name: 'Daniel', last_name: 'Hillier', rank: 105 },
  { first_name: 'Hao-Tong', last_name: 'Li', rank: 106 },
  { first_name: 'Garrick', last_name: 'Higgo', rank: 107 },
  { first_name: 'Denny', last_name: 'McCarthy', rank: 108 },
  { first_name: 'Kota', last_name: 'Kaneko', rank: 109 },
  { first_name: 'David', last_name: 'Lipsky', rank: 110 },
  { first_name: 'Angel', last_name: 'Ayora Fanegas', rank: 111 },
  { first_name: 'Tom', last_name: 'Hoge', rank: 112 },
  { first_name: 'Emiliano', last_name: 'Grillo', rank: 113 },
  { first_name: 'Oliver', last_name: 'Lindell', rank: 114 },
  { first_name: 'Jackson', last_name: 'Suber', rank: 115 },
  { first_name: 'Chris', last_name: 'Kirk', rank: 116 },
  { first_name: 'Kevin', last_name: 'Roy', rank: 117 },
  { first_name: 'Brooks', last_name: 'Koepka', rank: 118 },
  { first_name: 'Lee', last_name: 'Hodges', rank: 119 },
  { first_name: 'Hennie', last_name: 'Du Plessis', rank: 120 },
  { first_name: 'Chandler', last_name: 'Blanchet', rank: 121 },
  { first_name: 'Andy', last_name: 'Sullivan', rank: 122 },
  { first_name: 'Tony', last_name: 'Finau', rank: 123 },
  { first_name: 'Brandt', last_name: 'Snedeker', rank: 124 },
  { first_name: 'Ben', last_name: 'Kohles', rank: 125 },
  { first_name: 'William', last_name: 'Mouw', rank: 126 },
  { first_name: 'Doc', last_name: 'Redman', rank: 127 },
  { first_name: 'Adrien', last_name: 'Saddier', rank: 128 },
  { first_name: 'Richard', last_name: 'Sterne', rank: 129 },
  { first_name: 'Elvis', last_name: 'Smylie', rank: 130 },
  { first_name: 'Kevin', last_name: 'Yu', rank: 131 },
  { first_name: 'Josele', last_name: 'Ballester', rank: 132 },
  { first_name: 'Mark', last_name: 'Hubbard', rank: 133 },
  { first_name: 'Mikael', last_name: 'Lindberg', rank: 134 },
  { first_name: 'Tom', last_name: 'McKibbin', rank: 135 },
  { first_name: 'Daniel', last_name: 'Brown', rank: 136 },
  { first_name: 'Calum', last_name: 'Hill', rank: 137 },
  { first_name: 'Nacho', last_name: 'Elvira', rank: 138 },
  { first_name: 'Brian', last_name: 'Campbell', rank: 139 },
  { first_name: 'Cameron', last_name: 'Smith', rank: 140 },
  { first_name: 'Mackenzie', last_name: 'Hughes', rank: 141 },
  { first_name: 'Jacob Skov', last_name: 'Olesen', rank: 142 },
  { first_name: 'Laurie', last_name: 'Canter', rank: 143 },
  { first_name: 'JC', last_name: 'Ritchie', rank: 144 },
  { first_name: 'Travis', last_name: 'Smyth', rank: 145 },
  { first_name: 'Thorbjorn', last_name: 'Olesen', rank: 146 },
  { first_name: 'Marcus', last_name: 'Armitage', rank: 147 },
  { first_name: 'Seonghyeon', last_name: 'Kim', rank: 148 },
  { first_name: 'Michael', last_name: 'Hollick', rank: 149 },
  { first_name: 'Davis', last_name: 'Thompson', rank: 150 },
  { first_name: 'Taylor', last_name: 'Moore', rank: 151 },
  { first_name: 'Scott', last_name: 'Vincent', rank: 152 },
  { first_name: 'Dan', last_name: 'Bradbury', rank: 153 },
  { first_name: 'Ian', last_name: 'Holt', rank: 154 },
  { first_name: 'Bernd', last_name: 'Wiesberger', rank: 155 },
  { first_name: 'Takumi', last_name: 'Kanaya', rank: 156 },
  { first_name: 'Zac', last_name: 'Blair', rank: 157 },
  { first_name: 'Cole', last_name: 'Sherwood', rank: 158 },
  { first_name: 'Doug', last_name: 'Ghim', rank: 159 },
  { first_name: 'Joakim', last_name: 'Lagergren', rank: 160 },
  { first_name: 'Beau', last_name: 'Hossler', rank: 161 },
  { first_name: 'Thriston', last_name: 'Lawrence', rank: 162 },
  { first_name: 'Victor', last_name: 'Perez', rank: 163 },
  { first_name: 'Ross', last_name: 'Steelman', rank: 164 },
  { first_name: 'Jesper', last_name: 'Svensson', rank: 165 },
  { first_name: 'Davis', last_name: 'Lamb', rank: 166 },
  { first_name: 'Chandler', last_name: 'Phillips', rank: 167 },
  { first_name: 'Billy', last_name: 'Horschel', rank: 168 },
  { first_name: 'Martin', last_name: 'Couvra', rank: 169 },
  { first_name: 'Zachary', last_name: 'Bauchou', rank: 170 },
  { first_name: 'Jhonattan', last_name: 'Vegas', rank: 171 },
  { first_name: 'Davis', last_name: 'Bryant', rank: 172 },
  { first_name: 'Carlos', last_name: 'Ortiz', rank: 173 },
  { first_name: 'Adrien', last_name: 'Dumont De Chassart', rank: 174 },
  { first_name: 'Sergio', last_name: 'Garcia', rank: 175 },
  { first_name: 'Davis', last_name: 'Riley', rank: 176 },
  { first_name: 'Kazuki', last_name: 'Higa', rank: 177 },
  { first_name: 'Jorge', last_name: 'Campillo', rank: 178 },
  { first_name: 'Matt', last_name: 'Kuchar', rank: 179 },
  { first_name: 'Vince', last_name: 'Whaley', rank: 180 },
  { first_name: 'Jeremy', last_name: 'Gandon', rank: 181 },
  { first_name: 'Chad', last_name: 'Ramey', rank: 182 },
  { first_name: 'Austin', last_name: 'Eckroat', rank: 183 },
  { first_name: 'Adam', last_name: 'Schenk', rank: 184 },
  { first_name: 'Erik', last_name: 'Van Rooyen', rank: 185 },
  { first_name: 'Dean', last_name: 'Burmester', rank: 186 },
  { first_name: 'Carson', last_name: 'Young', rank: 187 },
  { first_name: 'A.J.', last_name: 'Ewart', rank: 188 },
  { first_name: 'Peter', last_name: 'Uihlein', rank: 189 },
  { first_name: 'Zecheng', last_name: 'Dou', rank: 190 },
  { first_name: 'Karl', last_name: 'Vilips', rank: 191 },
  { first_name: 'Julien', last_name: 'Guerrier', rank: 192 },
  { first_name: 'Joe', last_name: 'Highsmith', rank: 193 },
  { first_name: 'Ewen', last_name: 'Ferguson', rank: 194 },
  { first_name: 'Richard T.', last_name: 'Lee', rank: 195 },
  { first_name: 'Jay', last_name: 'Card', rank: 196 },
  { first_name: 'Drew', last_name: 'Nesbitt', rank: 197 },
  { first_name: 'Alistair', last_name: 'Docherty', rank: 198 },
  { first_name: 'Byeong Hun', last_name: 'An', rank: 199 },
  { first_name: 'Alejandro', last_name: 'Del Rey', rank: 200 },
];

const rankingsList: RankingRow[] = players.map(({ first_name, last_name, rank }) => ({
  player: {
    fullName: `${first_name} ${last_name}`.replace(/\s+/g, ' ').trim(),
  },
  rank,
}));

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'GET') {
    res.status(405).appendHeader('Allow', 'GET').end();
    return;
  }

  res.status(200).json({ rankingsList });
}
